### ISSUE TITLE
你好，运行过程遇到了报错，不知道能否协助解答

### ISSUE THREAD

**Issue by nsv2051** [bitis/ykt#2]
Failed loading /www/server/php/56/lib/php/extensions/no-debug-non-zts-20131226/opcache.so:  /www/server/php/56/lib/php/extensions/no-debug-non-zts-20131226/opcache.so: undefined symbol: _zval_ptr_dtor
Failed loading /usr/local/zend/php56/ZendGuardLoader.so:  /usr/local/zend/php56/ZendGuardLoader.so: undefined symbol: _zval_ptr_dtor
2022-08-17 20:39:17	政府采购代理机构基本规则	已完成
2022-08-17 20:39:17	政府采购代理机构应知应会的基本概念	未学完
2022-08-17 20:39:17	何谓政府采购？(时长：156s)	播放: 	已学完	 答题：0/0
2022-08-17 20:39:17	如何理解政府采购法的适用范围？(时长：392s)	播放: 	已学完	 答题：1/1
2022-08-17 20:39:17	如何理解财政性资金？(时长：377s)	播放: 	已学完	 答题：1/1
2022-08-17 20:39:17	政府采购应当遵循什么原则？(时长：157s)	播放: 	已学完	 答题：0/0
2022-08-17 20:39:17	政府采购当事人有哪些？还有哪些参加方？(时长：427s)	播放: 	已学完	 答题：2/2
2022-08-17 20:39:17	什么是集中采购、分散采购，什么是集中采购目录？(时长：223s)	播放: 	已学完	 答题：1/1
2022-08-17 20:39:17	限额标准与数额标准有什么不同？(时长：701s)	播放: 	已学完	 答题：2/2
2022-08-17 20:39:17	如何理解政府采购的程序？(时长：661s)	播放: 	已学完	 答题：0/0
2022-08-17 20:39:17	政府购买服务和政府采购服务有什么区别？(时长：524s)	播放: 	已学完	 答题：2/2
2022-08-17 20:39:17	如何理解PPP与政府采购的关系？(时长：176s)	播放: 	已学完	 答题：0/0
2022-08-17 20:39:17	采购代理机构的权利、责任有哪些？(时长：142s)	播放: 	已学完	 答题：0/0
2022-08-17 20:39:17	采购代理机构如何进行登记、变更名录信息？注销时应注意什么？(时长：122s)	播放: 	已学完	 答题：0/0
2022-08-17 20:39:17	采购代理机构应当具备什么条件？(时长：173s)	播放: 	已学完	 答题：0/0
2022-08-17 20:39:17	如何理解五名以上专职从业人员？(时长：100s)	播放: 	已学完	 答题：0/0
2022-08-17 20:39:17	代理机构如何不断提升业务水平？(时长：623s)	播放: 	已学完	 答题：1/1
2022-08-17 20:39:17	代理机构如何应对采购人的倾向性？(时长：122s)	播放: 	0%	 答题：0/0
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Console\Output\ConsoleOutput::createProgressBar() in /home/ykt/app.php:62
Stack trace:
#0 /home/ykt/vendor/symfony/console/Command/Command.php(296): Closure->{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /home/ykt/vendor/symfony/console/SingleCommandApplication.php(52): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /home/ykt/vendor/symfony/console/Application.php(1024): Symfony\Component\Console\SingleCommandApplication->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/ykt/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Component\Console\SingleCommandApplication), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/ykt/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /home/ykt/vendor/symfony/console/SingleCommandApplication.php(65): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/ykt/app.php(98): Symfony\Component\Console\SingleCommandApplication->run()
#7 {main}
  thrown in /home/ykt/app.php on line 62

Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Console\Output\ConsoleOutput::createProgressBar() in /home/ykt/app.php:62
Stack trace:
#0 /home/ykt/vendor/symfony/console/Command/Command.php(296): Closure->{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /home/ykt/vendor/symfony/console/SingleCommandApplication.php(52): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /home/ykt/vendor/symfony/console/Application.php(1024): Symfony\Component\Console\SingleCommandApplication->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/ykt/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Component\Console\SingleCommandApplication), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/ykt/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /home/ykt/vendor/symfony/console/SingleCommandApplication.php(65): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/ykt/app.php(98): Symfony\Component\Console\SingleCommandApplication->run()
#7 {main}
  thrown in /home/ykt/app.php on line 62

**Comment by bitis** [comment]
PHP version >= 7.4

**Comment by nsv2051** [comment]
`Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Console\Output\ConsoleOutput::createProgressBar() in /home/ykt/app.php:62
Stack trace:
#0 /home/ykt/vendor/symfony/console/Command/Command.php(296): Closure->{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /home/ykt/vendor/symfony/console/SingleCommandApplication.php(52): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /home/ykt/vendor/symfony/console/Application.php(1024): Symfony\Component\Console\SingleCommandApplication->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/ykt/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Component\Console\SingleCommandApplication), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/ykt/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /home/ykt/vendor/symfony/console/SingleCommandApplication.php(65): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/ykt/app.php(98): Symfony\Component\Console\SingleCommandApplication->run()
#7 {main}
  thrown in /home/ykt/app.php on line 62`
你好，目前PHP环境是8.0，这是最新的报错

**Comment by nsv2051** [comment]
`Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Console\Output\ConsoleOutput::createProgressBar() in /home/ykt/app.php:62
Stack trace:
#0 /home/ykt/vendor/symfony/console/Command/Command.php(296): Closure->{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /home/ykt/vendor/symfony/console/SingleCommandApplication.php(52): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /home/ykt/vendor/symfony/console/Application.php(1024): Symfony\Component\Console\SingleCommandApplication->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/ykt/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Component\Console\SingleCommandApplication), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Componen in /home/ykt/app.php on line 62`
这是php7.4的报错

**Comment by bitis** [comment]
已修复
